LCU/mvc/Controllers/AlumnoController.cs
using DTOS;
using IServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    [Authorize(Roles = "Admin,UTP,DAEM")]
    public class AlumnoController : Controller
    {
        IAlumnoService _alumnoService;
        ICursoService _cursoService;
        IAlumnoCursoService _alumnoCursoService;
        public AlumnoController(IAlumnoService alumnoService, ICursoService cursoService, IAlumnoCursoService alumnoCursoService)
        {
            _alumnoService = alumnoService;
            _cursoService = cursoService;
            _alumnoCursoService = alumnoCursoService;
        }
        // GET: Alumno
        public ActionResult Index()
        {
            //var _alumno = _alumnoService.GetAll();
            return View();
        }
        [HttpGet]
        public JsonResult getAllAlumnos()
        {
            var alumno = _alumnoService.GetAll();
            return Json(alumno, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);

        }

        // GET: Alumno/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Alumno/Create
        public ActionResult Create()
        {
            ViewBag.cursos = _cursoService.GetAll();
            return View();
        }

        // POST: Alumno/Create
        [HttpPost]
        public ActionResult Create(AlumnoDTO alumno, string curso)
        {
            try
            {
                // TODO: Add insert logic here
                alumno.Estado = "A";
                alumno.FechaModificacion = DateTime.Now;
                alumno.IdUsuario = 1;
                if (_alumnoService.Create(alumno))
                {
                    var nvoAlumno = _alumnoService.GetAll().LastOrDefault();
                    AlumnoCursoDTO _alumnoCursoDTO = new AlumnoCursoDTO();
                    CursoDTO _cursoDto = new CursoDTO();
                    _cursoDto = _cursoService.GetById(int.Parse(curso));
                    alumno.Id = nvoAlumno.Id;
                    _alumnoCursoDTO.Alumno = alumno;
                    _alumnoCursoDTO.Año = DateTime.Now.Year;
                    _alumnoCursoDTO.Curso = _cursoDto;
                    _alumnoCursoDTO.Estado = "A";
                    _alumnoCursoDTO.FechaModificacion = DateTime.Now;
                    _alumnoCursoDTO.IdUsuario = 1;
                    if (_alumnoCursoService.Create(_alumnoCursoDTO))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    return View();
                }

            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Alumno/Edit/5
        public ActionResult Edit(int id)
        {
            var alumno = _alumnoService.GetById(id);
            ViewBag.cursos = _cursoService.GetAll();
            ViewBag.cursoSel = _alumnoCursoService.GetAlumnoCursoByIds(id, DateTime.Now.Year).Curso.Id;
            return View(alumno);
        }

        // POST: Alumno/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, AlumnoDTO alumno, string curso)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // TODO: Add update logic here
                    alumno.Estado = "A";
                    alumno.FechaModificacion = DateTime.Now;
                    alumno.IdUsuario = 1;
                    if (_alumnoService.Update(alumno))
                    {
                        var _cursoDto = _cursoService.GetById(int.Parse(curso));
                        var _alumnoCursoDTO = _alumnoCursoService.GetAlumnoCursoByIds(alumno.Id, DateTime.Now.Year);
                        _alumnoCursoDTO.Alumno = alumno;
                        _alumnoCursoDTO.Curso = _cursoDto;
                        _alumnoCursoDTO.Estado = "A";
                        _alumnoCursoDTO.FechaModificacion = DateTime.Now;
                        _alumnoCursoDTO.IdUsuario = 1;
                        
                        if (_alumnoCursoService.Update(_alumnoCursoDTO))
                        {
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            return View();
                        }
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                var msg = e;
                ViewBag.cursos = _cursoService.GetAll();
                return View();
            }
        }

        // GET: Alumno/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Alumno/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LCU/mvc/Controllers/AsignaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTOS;
using IServices;

namespace mvc.Controllers
{
    [Authorize(Roles = "Admin,UTP,DAEM")]
    public class AsignaturaController : Controller
    {
        IAsignaturaService _asignaturaService;
        public AsignaturaController(IAsignaturaService asignaturaService)
        {
            _asignaturaService = asignaturaService;
        }
        // GET: Asignatura
        public ActionResult Index()
        {
            var _asignatura = _asignaturaService.GetAll();
            return View(_asignatura);
        }

        // GET: Asignatura/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Asignatura/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Asignatura/Create
        [HttpPost]
        public ActionResult Create(AsignaturaDTO asignatura)
        {
            try
            {
                // TODO: Add insert logic here
                asignatura.Estado = "A";
                asignatura.FechaModificacion = DateTime.Now;
                asignatura.IdUsuario = 1;
                if (_asignaturaService.Create(asignatura))
                {
                    return RedirectToAction("Index");
                }
                else {
                    return View();
                }

                
            }
            catch
            {
                return View();
            }
        }

        // GET: Asignatura/Edit/5
        public ActionResult Edit(int id)
        {
            var asignatura = _asignaturaService.GetById(id);
            return View(asignatura);
        }

        // POST: Asignatura/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, AsignaturaDTO asignatura)
        {
            try
            {
                // TODO: Add update logic here
                asignatura.Estado = "A";
                asignatura.FechaModificacion = DateTime.Now;
                asignatura.IdUsuario = 1;
                if (_asignaturaService.Update(asignatura))
                {
                    return RedirectToAction("Index");
                }
                else {
                    return View();
                }
                
            }
            catch
            {
                return View();
            }
        }

        // GET: Asignatura/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Asignatura/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LCU/mvc/Controllers/DocenteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTOS;
using IServices;

namespace mvc.Controllers
{
    [Authorize(Roles = "Admin,UTP,DAEM")]
    public class DocenteController : Controller
    {
        IDocenteService _docenteService;
        public DocenteController(IDocenteService docenteService)
        {
            _docenteService = docenteService;
        }


        // GET: Docente
        public ActionResult Index()
        {
            var _docente = _docenteService.GetAll();
            return View(_docente);
        }

        // GET: Docente/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Docente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Docente/Create
        [HttpPost]
        public ActionResult Create(DocenteDTO docente)
        {
            try
            {
                // TODO: Add insert logic here
                docente.Estado = "A";
                docente.FechaModificacion = DateTime.Now;
                docente.IdUsuario = 1;
                if (_docenteService.Create(docente))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch(Exception e )
            {

                return View();
            }
        }

        // GET: Docente/Edit/5
        public ActionResult Edit(int id)
        {
            var docente = _docenteService.GetById(id);
            return View(docente);
        }

        // POST: Docente/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, DocenteDTO docente)
        {
            try
            {
                // TODO: Add update logic here
                docente.Estado = "A";
                docente.FechaModificacion = DateTime.Now;
                docente.IdUsuario = 1;
                if (_docenteService.Update(docente)) {
                    return RedirectToAction("Index");
                }
                else {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Docente/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Docente/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LCU/mvc/Controllers/PruebaController.cs
using IServices;
using mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    [Authorize(Roles = "Admin,UTP,DAEM")]
    public class PruebaController : Controller
    {
        IPruebaService _pruebaService;
        IPreguntaService _preguntaService;

        public PruebaController(IPruebaService pruebaService, IPreguntaService preguntaService)
        {
            _pruebaService = pruebaService;
            _preguntaService = preguntaService;
        }

        // GET: Prueba
        public ActionResult Index()
        {
            var pruebas = _pruebaService.GetAll().OrderBy(x=>x.Id);
            return View(pruebas);
        }

        // GET: Prueba/Details/5
        public ActionResult Details(int id)
        {
            var prueba = _pruebaService.GetById(id);
            return View(prueba);
        }

        // GET: Prueba/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Prueba/Create
        [HttpPost]
        public ActionResult Create(PruebaPreguntas pp)
        {
            try
            {
                // Insertar en orden;
                //primero la prueba, lo que devuelve el id, luego ese id se agrega a las preguntas y finalmente se agregan las preguntas
                var user = 1;
                var estado = "A";
                var ahora = DateTime.Now;
                pp.Prueba.IdUsuario = user;
                pp.Prueba.Estado = estado;
                pp.Prueba.FechaModificacion = ahora;

                if (_pruebaService.Create(pp.Prueba))
                {
                    var id = _pruebaService.GetAll().LastOrDefault();
                    foreach (var item in pp.Preguntas)
                    {
                        item.Prueba = id;
                        item.IdUsuario = user;
                        item.Estado = estado;
                        item.FechaModificacion = ahora;
                    }
                    if (_preguntaService.Create(pp.Preguntas))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Prueba/Edit/5
        public ActionResult Edit(int id)
        {
            var prueba = _pruebaService.GetById(id);
            ViewBag.preguntas = _preguntaService.GetPreguntasByPrueba(id);
            return View(prueba);
        }

        // POST: Prueba/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, PruebaPreguntas pp)
        {
            try
            {
                var user = 1;
                var estado = "A";
                var ahora = DateTime.Now;

                var prueba = _pruebaService.GetById(id);
                prueba.IdUsuario = user;
                prueba.FechaModificacion = ahora;
                foreach (var item in pp.Preguntas)
                {
                    item.Prueba = prueba;
                    item.IdUsuario = user;
                    item.Estado = estado;
                    item.FechaModificacion = ahora;
                }
                _preguntaService.Update(pp.Preguntas);
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                var prueba = _pruebaService.GetById(id);
                ViewBag.preguntas = _preguntaService.GetPreguntasByPrueba(id);
                return View(prueba);
            }
        }

        // GET: Prueba/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Prueba/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LCU/mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Alumnos", "Index", "Alumno")</li>
                    <li>@Html.ActionLink("Asignaturas", "Index", "Asignatura")</li>
                    <li>@Html.ActionLink("Cursos", "Index", "Cursos")</li>
                    <li>@Html.ActionLink("Docentes", "Index", "Docente")</li>
                    <li>@Html.ActionLink("Pruebas", "Index", "Prueba")</li>
                    <li>@Html.ActionLink("Rendicion de Pruebas", "Index", "Rendicion")</li>
                    <li>@Html.ActionLink("Resultados", "Index", "Resultado")</li>
                    @* Desde aca van los usuarios, hay que ver como hacemos que no lo vean todos *@
                    <li>@Html.ActionLink("Usuarios", "Index", "Usuario")</li>
                    <li>@Html.ActionLink("Perfiles", "Index", "Perfil")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - N-Tec Ltda.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LCU/mvc/Views/Shared/_lcu.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liceo Corina Urbina - @ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Sistema en Línea</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#" data-toggle="modal" data-target="#login-modal"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row content">
            <div class="col-md-2 sidenav">
                <ul class="nav nav-pills nav-stacked">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Alumnos", "Index", "Alumno")</li>
                    <li>@Html.ActionLink("Asignaturas", "Index", "Asignatura")</li>
                    <li>@Html.ActionLink("Cursos", "Index", "Cursos")</li>
                    <li>@Html.ActionLink("Docentes", "Index", "Docente")</li>
                    <li>@Html.ActionLink("Pruebas", "Index", "Prueba")</li>
                    <li>@Html.ActionLink("Rendicion de Pruebas", "Index", "Rendicion")</li>
                    @*<li>@Html.ActionLink("Resultados", "Index", "Resultado")</li>*@
                    <li>@Html.ActionLink("Informes", "Index", "Informes")</li>
                    @* Desde aca van los usuarios, hay que ver como hacemos que no lo vean todos *@
                    <li><br /></li>
                    <li>@Html.ActionLink("Usuarios", "Index", "Home")</li>
                    <li>@Html.ActionLink("Perfiles", "Index", "Home")</li>
                </ul><br>
            </div>
            <div class="col-md-10">
                <div class="container body-content">
                    @RenderBody()
                </div>
                
            </div>
        </div>
        <div>
            <br />
            <footer class="text-center">
                <p>&copy; @DateTime.Now.Year - SYJ Consultores. </p>
                <p>Desarrollado por <a href="http://www.n-tec.cl">N-Tec Ltda.</a> </p>
            </footer>
        </div>
    </div>
    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="loginmodal-container">
                <h1>Inicio de Sesion</h1>
                <br>
                <form action="@Url.Action("Login","Account")?ReturnUrl=" method="post">
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <input type="text" name="model.UserName" placeholder="Usuario">
                        <input type="password" name="model.Password" placeholder="Contraseña">
                        <input type="hidden" name="model.RememberMe" value="true" />
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-12">
                            <button name="login" class="btn btn-lg btn-primary" id="login">Iniciar Sesion</button>
                        </div>

                    </div>
                </form>

                @*<div class="login-help">
                     <a href="#">Register</a> - <a href="#">Forgot Password</a>
                  </div>*@
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>