LCU/mvc/Controllers/RendicionController.cs
using IServices;
using mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    [Authorize(Roles = "Admin,UTP,DAEM")]
    public class RendicionController : Controller
    {
        IPruebaService _pruebaService;
        IRendicionService _rendicionService;
        IResultadoService _resultadoService;
        ICursoService _cursoService;
        IAlumnoService _alumnoService;
        IPreguntaService _preguntaService;

         public RendicionController(IPruebaService pruebaService, IRendicionService rendicionService, 
             IResultadoService resultadoService, ICursoService cursoService,IAlumnoService alumnoService,
             IPreguntaService preguntaService)
        {
            _pruebaService = pruebaService;
            _rendicionService = rendicionService;
            _resultadoService = resultadoService;
            _cursoService = cursoService;
            _alumnoService = alumnoService;
            _preguntaService = preguntaService;
        }


        // GET: Rendicion
        public ActionResult Index()
        {
            var rendicion = _rendicionService.GetAll();
            return View(rendicion);
        }

        // GET: Rendicion/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Rendicion/Create
        public ActionResult Create()
        {
            ViewBag.cursos = _cursoService.GetAll();
            ViewBag.pruebas = _pruebaService.GetAll();
            return View();
        }

        // POST: Rendicion/Create
        [HttpPost]
        public ActionResult Create(List<AlumnoPruebaResultado> data)
        {
            var user = 1;
            var estado = "A";
            var ahora = DateTime.Now;
            try
            {
                foreach (var item in data)
                {
                    item.AlumnoPrueba.IdUsuario = user;
                    item.AlumnoPrueba.Estado = estado;
                    item.AlumnoPrueba.FechaModificacion = ahora;
                    //item.AlumnoPrueba.Alumno = _alumnoService.GetById(item.AlumnoPrueba.Alumno.Id);
                    //item.AlumnoPrueba.Prueba = _pruebaService.GetById(item.AlumnoPrueba.Prueba.Id);
                    if (_rendicionService.Create(item.AlumnoPrueba))
                    {
                        var idAlumnoPrueba = _rendicionService.GetAll().LastOrDefault();
                        foreach (var key in item.Resultados)
                        {
                            key.Estado = estado;
                            key.FechaModificacion = ahora;
                            key.IdUsuario = user;
                            key.AlumnoPrueba = idAlumnoPrueba;
                            //key.Pregunta = _preguntaService.GetById(key.Pregunta.Id);
                            if (_resultadoService.Create(key))
                            {
                                var ok = true;
                            }
                            else
                            {
                                return View();
                            }
                        }
                    }
                    else
                    {
                        return View();
                    }
                }
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                var msg = e.Message;
                throw e;
            }
        }

        // GET: Rendicion/Edit/5
        public ActionResult Edit(int id = 0)
        {
            ViewBag.cursos = _cursoService.GetAll();
            ViewBag.pruebas = _pruebaService.GetAll();
            return View();
        }

        // POST: Rendicion/Edit/5
        [HttpPost]
        public ActionResult Edit(List<AlumnoPruebaResultado> data)
        {
            var user = 1;
            var estado = "A";
            var ahora = DateTime.Now;
            try
            {
                foreach (var item in data)
                {
                    item.AlumnoPrueba = _rendicionService.getByAlumnoPruebaIds(item.AlumnoPrueba.Alumno.Id, item.AlumnoPrueba.Prueba.Id);

                    item.AlumnoPrueba.IdUsuario = user;
                    item.AlumnoPrueba.Estado = estado;
                    item.AlumnoPrueba.FechaModificacion = ahora;
                    if (_rendicionService.Update(item.AlumnoPrueba))
                    {
                        foreach (var key in item.Resultados)
                        {
                            var nuevo = _resultadoService.GetById(key.Id);

                            if (nuevo == null) {

                                key.Estado = estado;
                                key.FechaModificacion = ahora;
                                key.IdUsuario = user;
                                key.AlumnoPrueba = item.AlumnoPrueba;
                                nuevo = key;
                            }
                            else
                            {
                                

                                nuevo.Estado = estado;
                                nuevo.FechaModificacion = ahora;
                                nuevo.IdUsuario = user;
                                nuevo.AlumnoPrueba = item.AlumnoPrueba;
                                nuevo.Respuesta = key.Respuesta;
                            }
                            
                            if (_resultadoService.Update(nuevo))
                            {
                                var ok = true;
                            }
                            else
                            {
                                return View();
                            }
                        }
                    }
                    else
                    {
                        return View();
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                var msg = e.Message;
                throw e;
            }
        }

        // GET: Rendicion/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Rendicion/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public JsonResult getAlumnosByCurso(int id)
        {
            var alumnos = _alumnoService.GetAlumnosbyCurso(id);
            return Json(alumnos, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getPreguntasByPrueba(int id)
        {
            var preguntas = _preguntaService.GetPreguntasByPrueba(id);
            return Json(preguntas, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult getRespuestaByPreguntaAlumnoPrueba(int p, int a, int t)
        {
            var pregunta = _resultadoService.getRespuestaByPreguntaAlumnoPrueba(p,a,t);
            List<string> respuesta = new List<string>();
            if (pregunta != null)
            {
                respuesta.Add(pregunta.Respuesta);
                respuesta.Add("" + pregunta.AlumnoPrueba.Puntaje);
                respuesta.Add("" + pregunta.AlumnoPrueba.Nota);
                respuesta.Add("" + pregunta.Id);
            }
            else
            {
                respuesta.Add("");
                respuesta.Add("");
                respuesta.Add("");
                respuesta.Add("");
            }
            return Json(respuesta, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
    }
}

LCU/mvc/Views/Rendicion/Create.cshtml
@model mvc.Models.AlumnoPruebaResultado

@{
    ViewBag.Title = "Rendición de Pruebas";
}

<h2>Rendición de Pruebas</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingresar Rendicion de Pruebas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-4">
                    <label for="Curso">Curso</label>
                        <select id="Curso" class="form-control">
                            <option value="-1">-- Seleccione Curso --</option>
                            @foreach (var item in ViewBag.cursos)
                            {
                                <option value="@item.Id">@item.Curso - @item.Descripcion</option>
                            }
                        </select>
                </div>
                <div class="col-sm-2"></div>
                <div class="col-sm-4">
                    <label for="Prueba">Prueba</label>
                    <select id="Prueba" class="form-control">
                        <option value="-1">-- Seleccione Prueba --</option>
                        @foreach (var item in ViewBag.pruebas)
                        {
                            <option value="@item.Id">@item.Descripcion</option>
                        }
                    </select>
                    
                </div>
                <div class="col-sm-1"></div>
            </div>
            <br />
            <div style="overflow-x:auto">
                <table id="tbAlumnoRespuestas" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th colspan="2">Alumno</th>
                            <th>Puntaje</th>
                            <th>Nota Alumno</th>
                            <th id="thRespuestas">Respuestas</th>
                        </tr>
                    </thead>
                    <tbody>


                    </tbody>
                </table>
            </div>
            <br />
            <div class="row pull-right">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    @Html.ActionLink("Volver a la Lista", "Index", new object { }, new { @class = "btn btn-default" })
                    <input type="submit" value="Guardar" class="btn btn-success" id="guardar" />
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
    </div>
}

@section scripts{
    <script type="text/javascript">
        $(function () {
            $("#Curso").change(function () {
                if ($(this).val() !== "-1" && $("#Prueba").val() !== "-1") {
                    var idCurso = $(this).val();
                    var idPrueba = $("#Prueba").val();

                    var preguntas;

                    
                    $.getJSON("@Url.Action("getPreguntasByPrueba","Rendicion")?id="+idPrueba, function (data) {
                        agregaCabeceras(data);
                        var preguntas = data;
                        
                        $.getJSON("@Url.Action("getAlumnosByCurso","Rendicion")?id="+idCurso, function (data) {
                            generaTabla(data, preguntas);
                        });
                    });
                }
            });

            $("#Prueba").change(function () {
                if ($(this).val() !== "-1" && $("#Curso").val() !== "-1") {
                    var idPrueba = $(this).val();
                    var idCurso = $("#Curso").val();

                    $.getJSON("/Rendicion/getPreguntasByPrueba?id=" + idPrueba, function (data) {
                        agregaCabeceras(data);
                        var preguntas = data;
                        $.getJSON("/Rendicion/getAlumnosByCurso?id=" + idCurso, function (data) {
                            generaTabla(data, preguntas);
                        });
                    });
                }
            });
        });

        function agregaCabeceras(data) {
            var cabecera = $("#tbAlumnoRespuestas thead");
            cabecera.html("");
            cabecera.append("<tr>");
            cabecera.append("<th class='col-md-4' colspan='2'>Alumno</th>");
            cabecera.append("<th class='col-md-4'>Puntaje</th>");
            cabecera.append("<th class='col-md-4'>Nota Alumno</th>");
            for (var i = 0; i < data.length; i++) {
                cabecera.append("<th style='width:auto;'>Pregunta" + (i + 1) + "&nbsp; </th > ");
            }
            cabecera.append("</tr>")
        }

        function generaTabla(alumnos, preguntas) {
            var idPrueba = $("#Prueba").val();
            var tabla = $("#tbAlumnoRespuestas tbody");
            tabla.html("");
            var inlinea = "<tr>";
            var filinea = "</tr>";
            $.each(alumnos, function (index,item) {
                var linea = inlinea;
                linea += "<td>" + item.Rut + "-" + item.Dv + "<input type='hidden' name='data[" + index + "].AlumnoPrueba.Alumno.Id' value='"+item.Id+"' />  </td>";
                linea += "<td>" + item.Nombre + " " + item.ApellidoPaterno + " " + item.ApellidoMaterno + "<input type='hidden' name='data[" + index + "].AlumnoPrueba.Prueba.Id' value='" + idPrueba +"' /> </td>";
                linea += "<td><input type='number' name='data[" + index + "].AlumnoPrueba.puntaje' value=0 class='form-control'></td>"
                linea += "<td><input type='number' name='data[" + index + "].AlumnoPrueba.nota' value=0 class='form-control'></td>"
                $.each(preguntas, function (interno, datos) {
                    linea += "<td><input type='hidden' name='data[" + index + "].Resultados[" + interno + "].Pregunta.Id' value='" + datos.Id + "' />";
                    linea += "<input type= 'text' name= 'data[" + index + "].Resultados[" + interno + "].Respuesta' class='form-control' required >"
                    linea += "</td > "
                });

                linea += filinea;
                tabla.append(linea);
            });
        }

    </script>
}

LCU/mvc/Views/Rendicion/Edit.cshtml
@model mvc.Models.AlumnoPruebaResultado

@{
    ViewBag.Title = "Editar Rendicion de Pruebas";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editar Rendicion de Pruebas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-4">
                    <label for="Curso">Curso</label>
                    <select id="Curso" class="form-control">
                        <option value="-1">-- Seleccione Curso --</option>
                        @foreach (var item in ViewBag.cursos)
                        {
                            <option value="@item.Id">@item.Curso - @item.Descripcion</option>
                        }
                    </select>
                </div>
                <div class="col-sm-2"></div>
                <div class="col-sm-4">
                    <label for="Prueba">Prueba</label>
                    <select id="Prueba" class="form-control">
                        <option value="-1">-- Seleccione Prueba --</option>
                        @foreach (var item in ViewBag.pruebas)
                        {
                            <option value="@item.Id">@item.Descripcion</option>
                        }
                    </select>

                </div>
                <div class="col-sm-1"></div>
            </div>
            <br />
            <div style="overflow-x:auto">
                <table id="tbAlumnoRespuestas" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th colspan="2">Alumno</th>
                            <th>Puntaje</th>
                            <th>Nota Alumno</th>
                            <th id="thRespuestas">Respuestas</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <br />
            <div class="row pull-right">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    @Html.ActionLink("Volver a la Lista", "Index", new object { }, new { @class = "btn btn-default" })
                    <input type="submit" value="Guardar" class="btn btn-success" id="guardar" />
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
    </div>
}

@section scripts{
    <script type="text/javascript">
        $(function () {
            $.ajaxSetup({
                async: false

            });

            $("#Curso").change(function () {
                if ($(this).val() !== "-1" && $("#Prueba").val() !== "-1") {
                    var idCurso = $(this).val();
                    var idPrueba = $("#Prueba").val();

                    var preguntas;


                    $.getJSON("@Url.Action("getPreguntasByPrueba","Rendicion")?id="+idPrueba, function (data) {
                        agregaCabeceras(data);
                        var preguntas = data;

                        $.getJSON("@Url.Action("getAlumnosByCurso","Rendicion")?id="+idCurso, function (data) {
                            generaTabla(data, preguntas);
                        });
                    });
                }
            });

            $("#Prueba").change(function () {
                if ($(this).val() !== "-1" && $("#Curso").val() !== "-1") {
                    var idPrueba = $(this).val();
                    var idCurso = $("#Curso").val();

                    $.getJSON("/Rendicion/getPreguntasByPrueba?id=" + idPrueba, function (data) {
                        agregaCabeceras(data);
                        var preguntas = data;
                        $.getJSON("/Rendicion/getAlumnosByCurso?id=" + idCurso, function (data) {
                            generaTabla(data, preguntas);
                        });
                    });
                }
            });

            $("#btnGuardar").click(function () {
                var con = confirm("¿Esta seguro que desea enviar la informacion?")
                if (con) {
                    $("#guardar").click();
                }
            })
        });

        function agregaCabeceras(data) {
            var cabecera = $("#tbAlumnoRespuestas thead");
            cabecera.html("");
            cabecera.append("<tr>");
            cabecera.append("<th class='col-md-4' colspan='2'>Alumno</th>");
            cabecera.append("<th class='col-md-4'>Puntaje</th>");
            cabecera.append("<th class='col-md-4'>Nota Alumno</th>");
            for (var i = 0; i < data.length; i++) {
                cabecera.append("<th style='width:auto;'>Pregunta" + (i + 1) + "&nbsp; </th > ");
            }
            cabecera.append("</tr>")
        }

        function generaTabla(alumnos, preguntas) {
            var idPrueba = $("#Prueba").val();
            var tabla = $("#tbAlumnoRespuestas tbody");
            tabla.html("");
            var inlinea = "<tr>";
            var filinea = "</tr>";
            $.each(alumnos, function (index,item) {
                var linea = inlinea;
                linea += "<td>" + item.Rut + "-" + item.Dv + "<input type='hidden' name='data[" + index + "].AlumnoPrueba.Alumno.Id' value='"+item.Id+"' />  </td>";
                linea += "<td>" + item.Nombre + " " + item.ApellidoPaterno + " " + item.ApellidoMaterno + "<input type='hidden' name='data[" + index + "].AlumnoPrueba.Prueba.Id' value='" + idPrueba + "' /> </td>";
                linea += "<td><input type='number' name='data[" + index + "].AlumnoPrueba.puntaje' value='#puntaje' class='form-control'></td>"
                linea += "<td><input type='number' name='data[" + index + "].AlumnoPrueba.nota' value='#nota' class='form-control'></td>"
                $.each(preguntas, function (interno, datos) {
                    var pagina = "@Url.Action("getRespuestaByPreguntaAlumnoPrueba","Rendicion")?p=" + datos.Id + "&a=" + item.Id + "&t=" + idPrueba;
                    console.log(pagina);
                    $.getJSON(pagina ,
                        function (json) {
                            linea = linea.replace('#puntaje', json[1]).replace('#nota',json[2]);
                            linea += "<td><input type='hidden' name='data[" + index + "].Resultados[" + interno + "].Pregunta.Id' value='" + datos.Id + "' />";
                            linea += "<input type= 'text' name= 'data[" + index + "].Resultados[" + interno + "].Respuesta' class='form-control' value='" + json[0] + "' required >"
                            linea += "<input type='hidden' name='data[" + index + "].Resultados[" + interno + "].Id' value='" + json[3] + "'>";
                            linea += "</td > "
                        }
                    );
                });

                linea += filinea;
                tabla.append(linea);
            });
        }

    </script>
}

LCU/mvc/Views/Rendicion/Index.cshtml
@model IEnumerable<DTOS.AlumnoPruebaDTO>

@{
    ViewBag.Title = "Listado de Rendiciones";
}

<h2>Listado de Rendiciones</h2>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-4">
            @Html.ActionLink("Nueva Rendicion de Pruebas", "Create", new object { }, new { @class = "btn btn-success" })
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-4">
            @Html.ActionLink("Editar Rendicion de Pruebas", "Edit", new object { }, new { @class = "btn btn-info" })
        </div>
        <div class="col-md-1"></div>
    </div>
</div>