LCU/mvc/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTOS;
using IServices;

namespace mvc.Controllers
{
    [Authorize(Roles = "Admin,UTP,DAEM")]
    public class CursosController : Controller
    {
        ICursoService _cursosService;

        public CursosController(ICursoService cursoService)
        {
            _cursosService = cursoService;
        }
        // GET: Cursos
        public ActionResult Index()
        {
            var _curso = _cursosService.GetAll();
            return View(_curso);
        }

        // GET: Cursos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cursos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cursos/Create
        [HttpPost]
        public ActionResult Create(CursoDTO vCurso)
        {
            try
            {
                // TODO: Add insert logic here
                vCurso.FechaModificacion = DateTime.Now;
                vCurso.Estado = "A";
                vCurso.IdUsuario = 1;

                if (_cursosService.Create(vCurso))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }

            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                return View();
            }
        }

        // GET: Cursos/Edit/5
        public ActionResult Edit(int id)
        {
            var curso = _cursosService.GetById(id);
            return View(curso);
        }

        // POST: Cursos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CursoDTO vcurso)
        {
            try
            {

                // TODO: Add update logic here
                vcurso.Estado = "A";
                vcurso.FechaModificacion = DateTime.Now;
                vcurso.IdUsuario = 1;
                vcurso.Id = id;
                if (_cursosService.Update(vcurso))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            


            }
            catch (Exception e)
            {
                var msg = e;
                return View();
    }
}

// GET: Cursos/Delete/5
public ActionResult Delete(int id)
{
    return View();
}

// POST: Cursos/Delete/5
[HttpPost]
public ActionResult Delete(int id, FormCollection collection)
{
    try
    {
        // TODO: Add delete logic here

        return RedirectToAction("Index");
    }
    catch
    {
        return View();
    }
}
    }
}

LCU/mvc/Views/Cursos/Create.cshtml
@model DTOS.CursoDTO

@{
    ViewBag.Title = "Create";
}

<h2>Nuevo Curso</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Curso, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Curso, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Curso, "", new { @class = "text-danger" })
                </div>

            <div class="col-md-6">
                    @Html.LabelFor(model => model.Descripcion,"Descripción", htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="row pull-right">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    @Html.ActionLink("Volver a la Lista", "Index", new object { }, new { @class = "btn btn-default" })
                    <input type="submit" value="Ingresar" class="btn btn-success" />
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
    </div>
}

LCU/mvc/Views/Cursos/Edit.cshtml
@model DTOS.CursoDTO

@{
    ViewBag.Title = "Editar Curso";
}

<h2>Editar Curso</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.Curso, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Curso, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Curso, "", new { @class = "text-danger" })
                </div>

                <div class="col-md-6">
                    @Html.LabelFor(model => model.Descripcion, "Descripción", htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="row pull-right">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    @Html.ActionLink("Volver a la Lista", "Index", new object { }, new { @class = "btn btn-default" })
                    <input type="submit" value="Guardar" class="btn btn-success" />
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
    </div>
}

LCU/mvc/Views/Cursos/Index.cshtml
@model IEnumerable<DTOS.CursoDTO>

@{
    ViewBag.Title = "Listado de Cursos";
}

<h2>Listado de Cursos</h2>

<p class="pull-right">
    @Html.ActionLink("Nuevo Curso", "Create",new object { },new {@class="btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaModificacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Curso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdUsuario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaModificacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Curso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            <a href="@Url.Action("Edit","Cursos", new {id=item.Id })" class="btn btn-info btn-xs">
                <span class="glyphicon glyphicon-pencil"></span>
                &nbsp;
                Editar
            </a>
                        @*@Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
        </td>
    </tr>
}

</table>