LCU/mvc/Controllers/InformesController.cs
using IServices;
using mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
namespace mvc.Controllers
{
    [Authorize(Roles = "Admin,UTP,DAEM")]
    public class InformesController : Controller
    {
        ICursoService _cursoService;
        IPruebaService _pruebaService;
        IReporteService _reporteService;

        public InformesController(ICursoService cursoService, IPruebaService pruebaService, IReporteService reporteService)
        {
            _cursoService = cursoService;
            _pruebaService = pruebaService;
            _reporteService=reporteService;
        }
        
        public ActionResult Index()
        {
            return View();
        }
        // GET: Informes/Create
        public ActionResult Create()
        {
            ViewBag.cursos = _cursoService.GetAll();
            ViewBag.pruebas = _pruebaService.GetAll();
            return View();
        }

        // GET: Informes/Create
        public ActionResult CreateAlumnoEje()
        {
            ViewBag.cursos = _cursoService.GetAll();
            ViewBag.pruebas = _pruebaService.GetAll();
            return View();
        }
        // GET: Informes/Create
        public ActionResult CreateEjePrueba()
        {
            ViewBag.cursos = _cursoService.GetAll();
            ViewBag.pruebas = _pruebaService.GetAll();
            return View();
        }

        [HttpGet]
        public JsonResult GetInformeByAlumno(int periodo, int curso, int prueba)
        {
            var resultado = _reporteService.getResultadoByAlumno(periodo, curso, prueba);
            return Json(resultado, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getInformeByAlumnoEje(int periodo, int curso, int prueba)
        {
            var resultado = _reporteService.getResultadoByAlumnoEje(periodo, curso, prueba);
            return Json(resultado, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult getInformeByEjePrueba(int periodo, int curso, int prueba)
        {
            var resultado = _reporteService.getResultadoByEjePrueba(periodo, curso, prueba);
            return Json(resultado, "application/json", Encoding.UTF8, JsonRequestBehavior.AllowGet);
        }
    }
}

LCU/mvc/Views/Informes/Create.cshtml
@{
    ViewBag.Title = "Resultado por Alumno";
}

<h2>Resultado por Alumno</h2>

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="row">
            <div class="col-sm-4">
                <label for="Periodo">Periodo</label>
                <select id="Periodo" class="form-control">
                    <option value="-1">-- Seleccione Periodo --</option>
                    <option value="2016">2016</option>
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                </select>
            </div>
            <div class="col-sm-4">
                <label for="Curso">Curso</label>
                <select id="Curso" class="form-control">
                    <option value="-1">-- Seleccione Curso --</option>
                    @foreach (var item in ViewBag.cursos)
                    {
                        <option value="@item.Id">@item.Curso - @item.Descripcion</option>
                    }
                </select>
            </div>
            <div class="col-sm-4">
                <label for="Prueba">Prueba</label>
                <select id="Prueba" class="form-control">
                    <option value="-1">-- Seleccione Prueba --</option>
                    @foreach (var item in ViewBag.pruebas)
                    {
                        <option value="@item.Id">@item.Descripcion</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="pull-right">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    @Html.ActionLink("Volver a la Lista", "Index", new object { }, new { @class = "btn btn-default" })
                    <input type="button" value="Generar" class="btn btn-success" id="generarReporte" />
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
        <hr />
        <div class="row" id="tbResult">
            <div class="table-responsive">
                <table class="table table-striped" id="tbResAlumnos">
                    <thead>
                        <tr>
                            <th>Linea</th>
                            <th>Curso</th>
                            <th>Rut</th>
                            <th>Nombres</th>
                            <th>Apellidos</th>
                            <th>Correctas</th>
                            <th>Omitidas</th>
                            <th>Puntaje</th>
                            <th>Nota</th>
                            <th>Nivel</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        $(function () {
            var buttonCommon = {
                exportOptions: {
                    format: {
                        body: function (data, row, column, node) {
                            // Strip $ from salary column to make it numeric
                            return column === 5 ?
                                data.replace(/[$,]/g, '') :
                                data;
                        }
                    }
                }
            };

            $("#tbResAlumnos").DataTable({
                "pageLength": 50,
                "responsive": true,
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
                "initComplete": function () {
                    this.api().columns('.select-filter').every(function () {
                        var column = this;
                        var select = $('<select><option value="">' + $(this.header()).html() + '</option></select>')
                            .appendTo($(column.header()).empty())
                            .on('change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            select.append('<option value="' + d + '">' + d + '</option>')
                        });
                    });
                },
                "dom": 'Bfrtip',
                "buttons": [
                    {
                        "extend": 'copyHtml5',
                        "text": 'Copiar',
                        "exportOptions": {
                            "columns": ':contains("Office")'
                        }
                    },
                    {
                        "extend": 'excelHtml5',
                        "text": 'Generar Excel',
                    },
                    {
                        "extend": 'pdfHtml5',
                        "text": 'Generar Pdf',
                    }
                ]
            });
            $("#generarReporte").click(function () {
                var periodo = $("#Periodo option:selected").val();
                var curso = $("#Curso option:selected").val();
                var prueba = $("#Prueba option:selected").val();
                var pagina = "@Url.Action("getInformeByAlumno", "Informes")";
                $.getJSON(pagina + "?periodo=" + periodo + "&curso=" + curso + "&prueba=" + prueba,
                    function (json) {
                        $("#tbResAlumnos").DataTable().clear();
                        var tabla = $("#tbResAlumnos").DataTable();
                        var arre = [];
                        $.each(json, function (index, data) {
                            arre.push([(index+1),data.Curso, data.Rut, data.Nombres, data.Apellidos, data.Correctas, data.Omitidas, data.Puntaje, data.Nota, data.Nivel]);
                        });
                        tabla.rows.add(arre).draw();
                    }
                );
            });

        });
    </script>
}

LCU/mvc/Views/Informes/CreateAlumnoEje.cshtml
@{
    ViewBag.Title = "Resultado por Alumno-Eje";
}

<h2>Resultado por Alumno-Eje</h2>

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="row">
            <div class="col-sm-4">
                <label for="Periodo">Periodo</label>
                <select id="Periodo" class="form-control">
                    <option value="-1">-- Seleccione Periodo --</option>
                    <option value="2016">2016</option>
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                </select>
            </div>
            <div class="col-sm-4">
                <label for="Curso">Curso</label>
                <select id="Curso" class="form-control">
                    <option value="-1">-- Seleccione Curso --</option>
                    @foreach (var item in ViewBag.cursos)
                    {
                        <option value="@item.Id">@item.Curso - @item.Descripcion</option>
                    }
                </select>
            </div>
            <div class="col-sm-4">
                <label for="Prueba">Prueba</label>
                <select id="Prueba" class="form-control">
                    <option value="-1">-- Seleccione Prueba --</option>
                    @foreach (var item in ViewBag.pruebas)
                    {
                        <option value="@item.Id">@item.Descripcion</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="pull-right">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    @Html.ActionLink("Volver a la Lista", "Index", new object { }, new { @class = "btn btn-default" })
                    <input type="button" value="Generar" class="btn btn-success" id="generarReporte" />
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="table-responsive">
                <table class="table table-striped" id="tbResAlumnos">
                    <thead>
                        <tr>
                            <th>Linea</th>
                            <th>Prueba</th>
                            <th class="select-filter">Curso</th>
                            <th>Rut</th>
                            <th>Nombres</th>
                            <th>Apellidos</th>
                            <th>Asignatura</th>
                            <th>Eje</th>
                            <th>Puntaje</th>
                            <th>Nivel</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        $(function () {
            var buttonCommon = {
                exportOptions: {
                    format: {
                        body: function (data, row, column, node) {
                            // Strip $ from salary column to make it numeric
                            return column === 5 ?
                                data.replace(/[$,]/g, '') :
                                data;
                        }
                    }
                }
            };

            $("#tbResAlumnos").DataTable({
                "pageLength": 50,
                "responsive": true,
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
                "initComplete": function () {
                    this.api().columns('.select-filter').every(function () {
                        var column = this;
                        var select = $('<select><option value="">' + $(this.header()).html() + '</option></select>')
                            .appendTo($(column.header()).empty())
                            .on('change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            select.append('<option value="' + d + '">' + d + '</option>')
                        });
                    });
                },
                "dom": 'Bfrtip',
                "buttons": [
                    {
                        "extend": 'copyHtml5',
                        "text": 'Copiar',
                        "exportOptions": {
                            "columns": ':contains("Office")'
                        }
                    },
                    {
                        "extend": 'excelHtml5',
                        "text": 'Generar Excel',
                    },
                    {
                        "extend": 'pdfHtml5',
                        "text": 'Generar Pdf',
                    }
                ]
            });
            $("#generarReporte").click(function () {
                var periodo = $("#Periodo option:selected").val();
                var curso = $("#Curso option:selected").val();
                var prueba = $("#Prueba option:selected").val();
                var pagina = "@Url.Action("getInformeByAlumnoEje", "Informes")";
                $.getJSON(pagina + "?periodo=" + periodo + "&curso=" + curso + "&prueba=" + prueba,
                    function (json) {
                        $("#tbResAlumnos").DataTable().clear();
                        var tabla = $("#tbResAlumnos").DataTable();
                        var arre = [];
                        $.each(json, function (index, data) {
                            arre.push([(index+1), data.Prueba, data.Curso, data.Rut, data.Nombres, data.Apellidos, data.Asignatura, data.Eje, data.Puntaje, data.Nivel]);
                        });
                        tabla.rows.add(arre).draw();
                    }
                );
            });

        });
    </script>
}

LCU/mvc/Views/Informes/CreateEjePrueba.cshtml
@{
    ViewBag.Title = "Resultado por Alumno-Eje";
}

<h2>Resultado por Alumno - Eje</h2>

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="row">
            <div class="col-sm-4">
                <label for="Periodo">Periodo</label>
                <select id="Periodo" class="form-control">
                    <option value="-1">-- Seleccione Periodo --</option>
                    <option value="2016">2016</option>
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                </select>
            </div>
            <div class="col-sm-4">
                <label for="Curso">Curso</label>
                <select id="Curso" class="form-control">
                    <option value="-1">-- Seleccione Curso --</option>
                    @foreach (var item in ViewBag.cursos)
                    {
                        <option value="@item.Id">@item.Curso - @item.Descripcion</option>
                    }
                </select>
            </div>
            <div class="col-sm-4">
                <label for="Prueba">Prueba</label>
                <select id="Prueba" class="form-control">
                    <option value="-1">-- Seleccione Prueba --</option>
                    @foreach (var item in ViewBag.pruebas)
                    {
                        <option value="@item.Id">@item.Descripcion</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="pull-right">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    @Html.ActionLink("Volver a la Lista", "Index", new object { }, new { @class = "btn btn-default" })
                    <input type="button" value="Generar" class="btn btn-success" id="generarReporte" />
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
        <hr />
        <div class="row" id="tbResult">
            <div class="table-responsive">
                <table class="table table-striped" id="tbResAlumnos">
                    <thead>
                        <tr>
                            <th rowspan="2">Eje o Habilidad</th>
                            <th rowspan="2">N° Alumnas</th>
                            <th id="thPrueba" colspan="4" class="text-center">Prueba</th>
                        </tr>
                        <tr>
                            <td>Nivel Bajo</td>
                            <td>Nivel Medio Bajo</td>
                            <td>Nivel Medio Alto</td>
                            <td>Nivel Alto</td>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        $(function () {
            var buttonCommon = {
                exportOptions: {
                    format: {
                        body: function (data, row, column, node) {
                            // Strip $ from salary column to make it numeric
                            return column === 5 ?
                                data.replace(/[$,]/g, '') :
                                data;
                        }
                    }
                }
            };

            $("#tbResAlumnos").DataTable({
                "pageLength": 50,
                "responsive": true,
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
                "initComplete": function () {
                    this.api().columns('.select-filter').every(function () {
                        var column = this;
                        var select = $('<select><option value="">' + $(this.header()).html() + '</option></select>')
                            .appendTo($(column.header()).empty())
                            .on('change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            select.append('<option value="' + d + '">' + d + '</option>')
                        });
                    });
                },
                "dom": 'Bfrtip',
                "buttons": [
                    {
                        "extend": 'copyHtml5',
                        "text": 'Copiar',
                        "exportOptions": {
                            "columns": ':contains("Office")'
                        }
                    },
                    {
                        "extend": 'excelHtml5',
                        "text": 'Generar Excel',
                    },
                    {
                        "extend": 'pdfHtml5',
                        "text": 'Generar Pdf',
                    }
                ]
            });
            $("#generarReporte").click(function () {
                var periodo = $("#Periodo option:selected").val();
                var curso = $("#Curso option:selected").val();
                var prueba = $("#Prueba option:selected").val();
                $("#thPrueba").html($("#Prueba option:selected").text());

                var pagina = "@Url.Action("getInformeByEjePrueba", "Informes")";
                $.getJSON(pagina + "?periodo=" + periodo + "&curso=" + curso + "&prueba=" + prueba,
                    function (json) {
                        $("#tbResAlumnos").DataTable().clear();
                        var tabla = $("#tbResAlumnos").DataTable();
                        var arre = [];
                        $.each(json, function (index, data) {
                            arre.push([data.EjeHabilidad, data.NroAlumnas, data.NivelBajo, data.NivelMedioBajo, data.NivelMedioAlto, data.NivelAlto]);
                        });
                        tabla.rows.add(arre).draw();
                    }
                );
            });

        });
    </script>
}

LCU/mvc/Views/Informes/Index.cshtml
@{
    ViewBag.Title = "Informes";
}

<h2>Informes</h2>
<hr />
<div class="form-group">
    <div class="row">
        <div class="col-md-4">
            @Html.ActionLink("Reporte Alumnos", "Create", new object { }, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-4">
            @Html.ActionLink("Resultado por Alumno - Eje", "CreateAlumnoEje", new object { }, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-4">
            @Html.ActionLink("Resultado por Eje - Prueba", "CreateEjePrueba", new object { }, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>